[package]
name = "basecoin"
version = "0.1.0"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.0.1"
cosmos-sdk-proto = "0.5.0"
cosmos_sdk = "0.1.1"
flex-error = { version = "0.2.0", features = [ "eyre_tracer" ] }
#ibc = "0.6.0"
ibc = { path = "../ibc-rs/modules" }
ics23 = "0.6.0"
prost = "0.7.0"
prost-types = "0.7.0"
serde = "1.0"
serde_json = "1.0"
sha2 = "0.9.2"
structopt = "0.3.21"
tendermint = "=0.21.0"
tendermint-abci = "=0.21.0"
tendermint-proto = "=0.21.0"
thiserror = "1.0"
tracing = "0.1.26"
tracing-subscriber = "0.2.18"
